name: news_app_clean_arch
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1

  # Comparing dart objects
  equatable: ^2.0.7
  
  # Service Locator
  get_it: ^9.2.0

  # Date Formatting
  intl: ^0.20.2

  # Database
  floor: ^1.5.0

  # Make request to api
  retrofit: ^4.9.1

  # Hooks
  flutter_hooks: ^0.21.3+1

  # Cached Images
  cached_network_image: ^3.4.1



dependency_overrides:
  build: ^4.0.0
  analyzer: ^6.4.1
  dart_style: ^3.1.1
  source_gen: '>=1.5.0 <4.1.1'


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^9.3.0
  build_runner: ^2.10.0
  json_serializable: ^6.11.3
  floor_generator: ^1.5.0
  flutter_lints: ^5.0.0



flutter:

  
  uses-material-design: true

 
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish/Mulish-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
